package producttest

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cozy-creator/cozy/internal/hostruntime"
)

// The installers, the README and every host-tool remedy name ONE command: the scripts
// cannot import Go, so this is where their copies are held to hostruntime.InstallCommand.
func TestInstallersRunTheHostToolCommand(t *testing.T) {
	words := strings.Fields(strings.ReplaceAll(hostruntime.InstallCommand, "'", ""))
	quoted := make([]string, 0, len(words)-1)
	for _, w := range words[1:] {
		quoted = append(quoted, "'"+w+"'")
	}
	want := map[string]string{
		"../../scripts/install.sh":  "HOST_TOOLS=(" + hostruntime.InstallCommand + ")",
		"../../scripts/install.ps1": "$hostTools = @(" + strings.Join(quoted, ", ") + ")",
		"../../README.md":           hostruntime.InstallCommand,
	}
	for path, line := range want {
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(body), line) {
			t.Errorf("%s does not carry the host-tool command\nwant: %s", path, line)
		}
	}
}

// The installer writes each shell's completion where that shell autoloads it, generated by
// the binary it just installed, and an upgrade overwrites what an older binary wrote.
func TestInstallerWritesShellCompletion(t *testing.T) {
	home, stub := t.TempDir(), t.TempDir()
	data, conf := filepath.Join(home, "data"), filepath.Join(home, "conf")
	tools := filepath.Join(stub, "tools")
	must(t, os.MkdirAll(tools, 0o755))
	// uv is stubbed: the host tools are not what this test is about, and a real install is a
	// network download. The stubs answer exactly what install.sh reads back.
	for name, body := range map[string]string{
		filepath.Join(stub, "uv"):            "case \"$1 $2\" in 'tool dir') echo " + tools + " ;; esac\n",
		filepath.Join(tools, "cozy-runtime"): "echo 'distribution: 0.0.0'\n", //cozy:allow stand-in Runtime the installer reads its version from
		filepath.Join(tools, "tfs"):          "echo 'tfs 0.0.0'\n",
	} {
		must(t, os.WriteFile(name, []byte("#!/bin/sh\n"+body), 0o755))
	}
	must(t, os.MkdirAll(filepath.Join(conf, "fish"), 0o755))
	_, zsh := exec.LookPath("zsh")
	hasZsh := zsh == nil
	if hasZsh {
		must(t, os.WriteFile(filepath.Join(home, ".zshrc"),
			[]byte("fpath=("+filepath.Join(data, "zsh", "site-functions")+" $fpath)\n"), 0o644))
	}
	files := map[string]string{
		"bash": filepath.Join(data, "bash-completion", "completions", "cozy"),
		"fish": filepath.Join(conf, "fish", "completions", "cozy.fish"),
		"zsh":  filepath.Join(data, "zsh", "site-functions", "_cozy"),
	}
	must(t, os.MkdirAll(filepath.Dir(files["bash"]), 0o755))
	must(t, os.WriteFile(files["bash"], []byte("# written by an older cozy\n"), 0o644))

	install := exec.Command("/usr/bin/nice", "-n", "19", "bash", "../../scripts/install.sh",
		"--binary", cozyBin, "--prefix", filepath.Join(home, "prefix"))
	install.Env = []string{"HOME=" + home, "XDG_DATA_HOME=" + data, "XDG_CONFIG_HOME=" + conf,
		"PATH=" + stub + ":/usr/local/bin:/usr/bin:/bin"}
	out, err := install.CombinedOutput()
	if err != nil {
		t.Fatalf("install: %v\n%s", err, out)
	}
	for shell, path := range files {
		got, err := os.ReadFile(path)
		if shell == "zsh" && !hasZsh {
			if err == nil {
				t.Errorf("zsh is not installed, yet %s was written", path)
			}
			continue
		}
		if err != nil {
			t.Fatalf("%s completion: %v\n%s", shell, err, out)
		}
		want, err := exec.Command(cozyBin, "completion", shell).Output()
		must(t, err)
		if string(got) != string(want) {
			t.Errorf("%s holds\n%s\nwant the installed binary's `cozy completion %s`:\n%s", path, got, shell, want)
		}
		if !strings.Contains(string(out), "complete: "+shell+" "+path) {
			t.Errorf("the installer did not report %s\n%s", path, out)
		}
	}
	if strings.Contains(string(out), "source <(cozy completion bash)") {
		t.Errorf("the installer still asks for an rc edit bash no longer needs\n%s", out)
	}
}
