// The machine's API (G/API.md): five calls on the machine's one TLS listener, whose leaf the
// client pins. Every call carries `authorization: Cozy-Cap <token>` metadata; Status may omit
// it (then it answers identity and the sealed readiness receipt only). Unknown fields are
// ignored. There are no version ranges: Status lists capabilities.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.4
// source: cozy/machine/v1/machine.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Machine_Status_FullMethodName  = "/cozy.machine.v1.Machine/Status"
	Machine_Run_FullMethodName     = "/cozy.machine.v1.Machine/Run"
	Machine_Control_FullMethodName = "/cozy.machine.v1.Machine/Control"
	Machine_Read_FullMethodName    = "/cozy.machine.v1.Machine/Read"
	Machine_Write_FullMethodName   = "/cozy.machine.v1.Machine/Write"
)

// MachineClient is the client API for Machine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MachineClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusFrame], error)
	// Submits when `spec` is set and `id` is new (idempotent on id per signer), then streams the
	// run's log from `after`. Without `spec` it attaches. Closing the stream never cancels.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*RunState, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFrame], error)
	Write(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFrame, WriteResult], error)
}

type machineClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineClient(cc grpc.ClientConnInterface) MachineClient {
	return &machineClient{cc}
}

func (c *machineClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Machine_ServiceDesc.Streams[0], Machine_Status_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, StatusFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_StatusClient = grpc.ServerStreamingClient[StatusFrame]

func (c *machineClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Machine_ServiceDesc.Streams[1], Machine_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_RunClient = grpc.ServerStreamingClient[RunEvent]

func (c *machineClient) Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*RunState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunState)
	err := c.cc.Invoke(ctx, Machine_Control_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Machine_ServiceDesc.Streams[2], Machine_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRequest, ReadFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_ReadClient = grpc.ServerStreamingClient[ReadFrame]

func (c *machineClient) Write(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFrame, WriteResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Machine_ServiceDesc.Streams[3], Machine_Write_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFrame, WriteResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_WriteClient = grpc.ClientStreamingClient[WriteFrame, WriteResult]

// MachineServer is the server API for Machine service.
// All implementations must embed UnimplementedMachineServer
// for forward compatibility.
type MachineServer interface {
	Status(*StatusRequest, grpc.ServerStreamingServer[StatusFrame]) error
	// Submits when `spec` is set and `id` is new (idempotent on id per signer), then streams the
	// run's log from `after`. Without `spec` it attaches. Closing the stream never cancels.
	Run(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error
	Control(context.Context, *ControlRequest) (*RunState, error)
	Read(*ReadRequest, grpc.ServerStreamingServer[ReadFrame]) error
	Write(grpc.ClientStreamingServer[WriteFrame, WriteResult]) error
	mustEmbedUnimplementedMachineServer()
}

// UnimplementedMachineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineServer struct{}

func (UnimplementedMachineServer) Status(*StatusRequest, grpc.ServerStreamingServer[StatusFrame]) error {
	return status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMachineServer) Run(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedMachineServer) Control(context.Context, *ControlRequest) (*RunState, error) {
	return nil, status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedMachineServer) Read(*ReadRequest, grpc.ServerStreamingServer[ReadFrame]) error {
	return status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedMachineServer) Write(grpc.ClientStreamingServer[WriteFrame, WriteResult]) error {
	return status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedMachineServer) mustEmbedUnimplementedMachineServer() {}
func (UnimplementedMachineServer) testEmbeddedByValue()                 {}

// UnsafeMachineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineServer will
// result in compilation errors.
type UnsafeMachineServer interface {
	mustEmbedUnimplementedMachineServer()
}

func RegisterMachineServer(s grpc.ServiceRegistrar, srv MachineServer) {
	// If the following call panics, it indicates UnimplementedMachineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Machine_ServiceDesc, srv)
}

func _Machine_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).Status(m, &grpc.GenericServerStream[StatusRequest, StatusFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_StatusServer = grpc.ServerStreamingServer[StatusFrame]

func _Machine_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).Run(m, &grpc.GenericServerStream[RunRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_RunServer = grpc.ServerStreamingServer[RunEvent]

func _Machine_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Machine_Control_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Control(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).Read(m, &grpc.GenericServerStream[ReadRequest, ReadFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_ReadServer = grpc.ServerStreamingServer[ReadFrame]

func _Machine_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MachineServer).Write(&grpc.GenericServerStream[WriteFrame, WriteResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Machine_WriteServer = grpc.ClientStreamingServer[WriteFrame, WriteResult]

// Machine_ServiceDesc is the grpc.ServiceDesc for Machine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Machine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cozy.machine.v1.Machine",
	HandlerType: (*MachineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Control",
			Handler:    _Machine_Control_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Status",
			Handler:       _Machine_Status_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Run",
			Handler:       _Machine_Run_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Machine_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Write",
			Handler:       _Machine_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "cozy/machine/v1/machine.proto",
}
