// The machine's API (G/API.md): five calls on the machine's one TLS listener, whose leaf the
// client pins. Every call carries `authorization: Cozy-Cap <token>` metadata; Status may omit
// it (then it answers identity and the sealed readiness receipt only). Unknown fields are
// ignored. There are no version ranges: Status lists capabilities.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.4
// source: cozy/machine/v1/machine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunKind int32

const (
	RunKind_RUN_KIND_CALL   RunKind = 0
	RunKind_RUN_KIND_JOB    RunKind = 1
	RunKind_RUN_KIND_WARM   RunKind = 2 // prepare only: install and download, then succeed
	RunKind_RUN_KIND_UPDATE RunKind = 3 // stage, verify and activate a software cohort at idle
)

// Enum value maps for RunKind.
var (
	RunKind_name = map[int32]string{
		0: "RUN_KIND_CALL",
		1: "RUN_KIND_JOB",
		2: "RUN_KIND_WARM",
		3: "RUN_KIND_UPDATE",
	}
	RunKind_value = map[string]int32{
		"RUN_KIND_CALL":   0,
		"RUN_KIND_JOB":    1,
		"RUN_KIND_WARM":   2,
		"RUN_KIND_UPDATE": 3,
	}
)

func (x RunKind) Enum() *RunKind {
	p := new(RunKind)
	*p = x
	return p
}

func (x RunKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cozy_machine_v1_machine_proto_enumTypes[0].Descriptor()
}

func (RunKind) Type() protoreflect.EnumType {
	return &file_cozy_machine_v1_machine_proto_enumTypes[0]
}

func (x RunKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunKind.Descriptor instead.
func (RunKind) EnumDescriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_CANCEL      Action = 1
	Action_ACTION_PAUSE       Action = 2
	Action_ACTION_RESUME      Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_CANCEL",
		2: "ACTION_PAUSE",
		3: "ACTION_RESUME",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_CANCEL":      1,
		"ACTION_PAUSE":       2,
		"ACTION_RESUME":      3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_cozy_machine_v1_machine_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_cozy_machine_v1_machine_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{1}
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`        // the caller's run id
	After         uint64                 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"` // stream the events after this sequence
	Spec          *RunSpec               `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`    // absent: attach to an existing run
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *RunRequest) GetSpec() *RunSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type RunSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  RunKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=cozy.machine.v1.RunKind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*RunSpec_Release
	//	*RunSpec_Installation
	//	*RunSpec_Local
	Source             isRunSpec_Source `protobuf_oneof:"source"`
	Entrypoint         string           `protobuf:"bytes,6,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Payload            []byte           `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"` // canonical JSON object of the function's parameters
	Inputs             []*InputFile     `protobuf:"bytes,8,rep,name=inputs,proto3" json:"inputs,omitempty"`   // objects uploaded with Write, bound to payload fields
	Models             []*ModelChoice   `protobuf:"bytes,9,rep,name=models,proto3" json:"models,omitempty"`
	BindingRevision    string           `protobuf:"bytes,10,opt,name=binding_revision,json=bindingRevision,proto3" json:"binding_revision,omitempty"` // the owner's binding revision the caller knows
	KnownResults       []*MemoResult    `protobuf:"bytes,11,rep,name=known_results,json=knownResults,proto3" json:"known_results,omitempty"`
	AttentionKernel    string           `protobuf:"bytes,12,opt,name=attention_kernel,json=attentionKernel,proto3" json:"attention_kernel,omitempty"`
	WeightsDestination string           `protobuf:"bytes,13,opt,name=weights_destination,json=weightsDestination,proto3" json:"weights_destination,omitempty"` // model://… for a job's weights outputs
	Hub                *HubAccess       `protobuf:"bytes,14,opt,name=hub,proto3" json:"hub,omitempty"`                                                         // held in memory for this run's preparation only
	Owner              string           `protobuf:"bytes,15,opt,name=owner,proto3" json:"owner,omitempty"`                                                     // the account that org-relative references of local code name
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunSpec) Reset() {
	*x = RunSpec{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSpec) ProtoMessage() {}

func (x *RunSpec) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSpec.ProtoReflect.Descriptor instead.
func (*RunSpec) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{1}
}

func (x *RunSpec) GetKind() RunKind {
	if x != nil {
		return x.Kind
	}
	return RunKind_RUN_KIND_CALL
}

func (x *RunSpec) GetSource() isRunSpec_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RunSpec) GetRelease() *Release {
	if x != nil {
		if x, ok := x.Source.(*RunSpec_Release); ok {
			return x.Release
		}
	}
	return nil
}

func (x *RunSpec) GetInstallation() string {
	if x != nil {
		if x, ok := x.Source.(*RunSpec_Installation); ok {
			return x.Installation
		}
	}
	return ""
}

func (x *RunSpec) GetLocal() *LocalSource {
	if x != nil {
		if x, ok := x.Source.(*RunSpec_Local); ok {
			return x.Local
		}
	}
	return nil
}

func (x *RunSpec) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *RunSpec) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunSpec) GetInputs() []*InputFile {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RunSpec) GetModels() []*ModelChoice {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *RunSpec) GetBindingRevision() string {
	if x != nil {
		return x.BindingRevision
	}
	return ""
}

func (x *RunSpec) GetKnownResults() []*MemoResult {
	if x != nil {
		return x.KnownResults
	}
	return nil
}

func (x *RunSpec) GetAttentionKernel() string {
	if x != nil {
		return x.AttentionKernel
	}
	return ""
}

func (x *RunSpec) GetWeightsDestination() string {
	if x != nil {
		return x.WeightsDestination
	}
	return ""
}

func (x *RunSpec) GetHub() *HubAccess {
	if x != nil {
		return x.Hub
	}
	return nil
}

func (x *RunSpec) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type isRunSpec_Source interface {
	isRunSpec_Source()
}

type RunSpec_Release struct {
	Release *Release `protobuf:"bytes,2,opt,name=release,proto3,oneof"`
}

type RunSpec_Installation struct {
	Installation string `protobuf:"bytes,3,opt,name=installation,proto3,oneof"` // one this machine already holds for the signer
}

type RunSpec_Local struct {
	Local *LocalSource `protobuf:"bytes,4,opt,name=local,proto3,oneof"`
}

func (*RunSpec_Release) isRunSpec_Source() {}

func (*RunSpec_Installation) isRunSpec_Source() {}

func (*RunSpec_Local) isRunSpec_Source() {}

type Release struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"` // org/name
	Release       string                 `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{2}
}

func (x *Release) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Release) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

// The manifest is a JSON object written with Write: {package: "local/<dist>", release,
// python_requires, python_version, source: {digest, length} (a tar of the project),
// wheels: [{name, digest, length}], requirements: {digest, length}}. Its members are objects
// the same signer wrote.
type LocalSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      string                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"` // sha256:<hex> of the manifest object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalSource) Reset() {
	*x = LocalSource{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSource) ProtoMessage() {}

func (x *LocalSource) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSource.ProtoReflect.Descriptor instead.
func (*LocalSource) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{3}
}

func (x *LocalSource) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

type InputFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`   // the payload field path, list index included
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"` // sha256:<hex>
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Order         uint32                 `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFile) Reset() {
	*x = InputFile{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFile) ProtoMessage() {}

func (x *InputFile) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFile.ProtoReflect.Descriptor instead.
func (*InputFile) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{4}
}

func (x *InputFile) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *InputFile) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *InputFile) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *InputFile) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *InputFile) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type ModelChoice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Parameter      string                 `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"` // a root slot parameter or full slot path
	Repository     string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Release        string                 `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	Lane           string                 `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"`
	Manifest       string                 `protobuf:"bytes,5,opt,name=manifest,proto3" json:"manifest,omitempty"` // sha256:<hex>, optional exact checkpoint
	ManifestLength uint64                 `protobuf:"varint,6,opt,name=manifest_length,json=manifestLength,proto3" json:"manifest_length,omitempty"`
	Adapters       []*Adapter             `protobuf:"bytes,7,rep,name=adapters,proto3" json:"adapters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelChoice) Reset() {
	*x = ModelChoice{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelChoice) ProtoMessage() {}

func (x *ModelChoice) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelChoice.ProtoReflect.Descriptor instead.
func (*ModelChoice) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{5}
}

func (x *ModelChoice) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *ModelChoice) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ModelChoice) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *ModelChoice) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *ModelChoice) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

func (x *ModelChoice) GetManifestLength() uint64 {
	if x != nil {
		return x.ManifestLength
	}
	return 0
}

func (x *ModelChoice) GetAdapters() []*Adapter {
	if x != nil {
		return x.Adapters
	}
	return nil
}

type Adapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Release       string                 `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	Lane          string                 `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"`
	Manifest      string                 `protobuf:"bytes,5,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Scale         string                 `protobuf:"bytes,6,opt,name=scale,proto3" json:"scale,omitempty"` // canonical decimal; empty means 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Adapter) Reset() {
	*x = Adapter{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adapter) ProtoMessage() {}

func (x *Adapter) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adapter.ProtoReflect.Descriptor instead.
func (*Adapter) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{6}
}

func (x *Adapter) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Adapter) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Adapter) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *Adapter) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *Adapter) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

func (x *Adapter) GetScale() string {
	if x != nil {
		return x.Scale
	}
	return ""
}

type MemoResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Operation         string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ComputationDigest string                 `protobuf:"bytes,2,opt,name=computation_digest,json=computationDigest,proto3" json:"computation_digest,omitempty"` // sha256:<hex>
	Result            []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                                                // the recorded canonical result document
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemoResult) Reset() {
	*x = MemoResult{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoResult) ProtoMessage() {}

func (x *MemoResult) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoResult.ProtoReflect.Descriptor instead.
func (*MemoResult) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{7}
}

func (x *MemoResult) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *MemoResult) GetComputationDigest() string {
	if x != nil {
		return x.ComputationDigest
	}
	return ""
}

func (x *MemoResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type HubAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`      // unix seconds
	CaDer         []byte                 `protobuf:"bytes,4,opt,name=ca_der,json=caDer,proto3" json:"ca_der,omitempty"`                   // an origin's private CA, when it has one
	ObjectHosts   []string               `protobuf:"bytes,5,rep,name=object_hosts,json=objectHosts,proto3" json:"object_hosts,omitempty"` // the Hub's object-storage hosts downloads may follow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubAccess) Reset() {
	*x = HubAccess{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubAccess) ProtoMessage() {}

func (x *HubAccess) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubAccess.ProtoReflect.Descriptor instead.
func (*HubAccess) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{8}
}

func (x *HubAccess) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *HubAccess) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HubAccess) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *HubAccess) GetCaDer() []byte {
	if x != nil {
		return x.CaDer
	}
	return nil
}

func (x *HubAccess) GetObjectHosts() []string {
	if x != nil {
		return x.ObjectHosts
	}
	return nil
}

type RunEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // 0: a preparation progress frame before the run is accepted
	AtMs     int64                  `protobuf:"varint,2,opt,name=at_ms,json=atMs,proto3" json:"at_ms,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunEvent_State
	//	*RunEvent_Progress
	//	*RunEvent_Product
	//	*RunEvent_Log
	//	*RunEvent_Outcome
	//	*RunEvent_Memo
	Event         isRunEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{9}
}

func (x *RunEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RunEvent) GetAtMs() int64 {
	if x != nil {
		return x.AtMs
	}
	return 0
}

func (x *RunEvent) GetEvent() isRunEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunEvent) GetState() *RunState {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *RunEvent) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *RunEvent) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Product); ok {
			return x.Product
		}
	}
	return nil
}

func (x *RunEvent) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *RunEvent) GetOutcome() *Outcome {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Outcome); ok {
			return x.Outcome
		}
	}
	return nil
}

func (x *RunEvent) GetMemo() *MemoRecord {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Memo); ok {
			return x.Memo
		}
	}
	return nil
}

type isRunEvent_Event interface {
	isRunEvent_Event()
}

type RunEvent_State struct {
	State *RunState `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

type RunEvent_Progress struct {
	Progress *Progress `protobuf:"bytes,4,opt,name=progress,proto3,oneof"`
}

type RunEvent_Product struct {
	Product *Product `protobuf:"bytes,5,opt,name=product,proto3,oneof"`
}

type RunEvent_Log struct {
	Log *LogLine `protobuf:"bytes,6,opt,name=log,proto3,oneof"`
}

type RunEvent_Outcome struct {
	Outcome *Outcome `protobuf:"bytes,7,opt,name=outcome,proto3,oneof"`
}

type RunEvent_Memo struct {
	Memo *MemoRecord `protobuf:"bytes,8,opt,name=memo,proto3,oneof"`
}

func (*RunEvent_State) isRunEvent_Event() {}

func (*RunEvent_Progress) isRunEvent_Event() {}

func (*RunEvent_Product) isRunEvent_Event() {}

func (*RunEvent_Log) isRunEvent_Event() {}

func (*RunEvent_Outcome) isRunEvent_Event() {}

func (*RunEvent_Memo) isRunEvent_Event() {}

type RunState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        uint64                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`     // this machine's run number
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`        // queued, preparing, running, paused, succeeded, failed, canceled
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"` // the log's head
	Attempt       uint32                 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Waiting       string                 `protobuf:"bytes,6,opt,name=waiting,proto3" json:"waiting,omitempty"` // why a queued run waits, for people
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunState) Reset() {
	*x = RunState{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunState) ProtoMessage() {}

func (x *RunState) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunState.ProtoReflect.Descriptor instead.
func (*RunState) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{10}
}

func (x *RunState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunState) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *RunState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunState) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RunState) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RunState) GetWaiting() string {
	if x != nil {
		return x.Waiting
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Fraction      float64                `protobuf:"fixed64,2,opt,name=fraction,proto3" json:"fraction,omitempty"` // -1: unknown
	Completed     uint64                 `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	Total         uint64                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	BytesDone     uint64                 `protobuf:"varint,5,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	BytesTotal    uint64                 `protobuf:"varint,6,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{11}
}

func (x *Progress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Progress) GetFraction() float64 {
	if x != nil {
		return x.Fraction
	}
	return 0
}

func (x *Progress) GetCompleted() uint64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *Progress) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Progress) GetBytesDone() uint64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

func (x *Progress) GetBytesTotal() uint64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

// One revision of an output: a single output is replaced by each, a list output grows.
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // a list item's 1-based index; 0 for a single output
	Rev           uint64                 `protobuf:"varint,3,opt,name=rev,proto3" json:"rev,omitempty"`
	Length        uint64                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Digest        string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"` // sha256:<hex> of these bytes
	MediaType     string                 `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Label         string                 `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	DurationUs    uint64                 `protobuf:"varint,8,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"` // media time, for a growing video
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{12}
}

func (x *Product) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Product) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Product) GetRev() uint64 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *Product) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Product) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Product) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Product) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Product) GetDurationUs() uint64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{13}
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // succeeded, failed, canceled
	Reason        *Reason                `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // the result's canonical JSON, assets as digests
	Outputs       []*Product             `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Triage        bool                   `protobuf:"varint,5,opt,name=triage,proto3" json:"triage,omitempty"` // Read{triage} answers its bundle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{14}
}

func (x *Outcome) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Outcome) GetReason() *Reason {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *Outcome) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Outcome) GetOutputs() []*Product {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Outcome) GetTriage() bool {
	if x != nil {
		return x.Triage
	}
	return false
}

type Reason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"` // request, runtime, author, machine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reason) Reset() {
	*x = Reason{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reason) ProtoMessage() {}

func (x *Reason) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reason.ProtoReflect.Descriptor instead.
func (*Reason) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{15}
}

func (x *Reason) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Reason) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Reason) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type MemoRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Operation         string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ComputationDigest string                 `protobuf:"bytes,2,opt,name=computation_digest,json=computationDigest,proto3" json:"computation_digest,omitempty"`
	Result            []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemoRecord) Reset() {
	*x = MemoRecord{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoRecord) ProtoMessage() {}

func (x *MemoRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoRecord.ProtoReflect.Descriptor instead.
func (*MemoRecord) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{16}
}

func (x *MemoRecord) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *MemoRecord) GetComputationDigest() string {
	if x != nil {
		return x.ComputationDigest
	}
	return ""
}

func (x *MemoRecord) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=cozy.machine.v1.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{17}
}

func (x *ControlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*ReadRequest_Output
	//	*ReadRequest_Triage
	//	*ReadRequest_Log
	Target        isReadRequest_Target `protobuf_oneof:"target"`
	Offset        uint64               `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	IfRev         uint64               `protobuf:"varint,5,opt,name=if_rev,json=ifRev,proto3" json:"if_rev,omitempty"` // nonzero: refuse (FAILED_PRECONDITION) unless the output is at this rev
	Tail          uint64               `protobuf:"varint,6,opt,name=tail,proto3" json:"tail,omitempty"`                // a log's newest bytes, from a line start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{18}
}

func (x *ReadRequest) GetTarget() isReadRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ReadRequest) GetOutput() *OutputTarget {
	if x != nil {
		if x, ok := x.Target.(*ReadRequest_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ReadRequest) GetTriage() string {
	if x != nil {
		if x, ok := x.Target.(*ReadRequest_Triage); ok {
			return x.Triage
		}
	}
	return ""
}

func (x *ReadRequest) GetLog() string {
	if x != nil {
		if x, ok := x.Target.(*ReadRequest_Log); ok {
			return x.Log
		}
	}
	return ""
}

func (x *ReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetIfRev() uint64 {
	if x != nil {
		return x.IfRev
	}
	return 0
}

func (x *ReadRequest) GetTail() uint64 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type isReadRequest_Target interface {
	isReadRequest_Target()
}

type ReadRequest_Output struct {
	Output *OutputTarget `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ReadRequest_Triage struct {
	Triage string `protobuf:"bytes,2,opt,name=triage,proto3,oneof"` // a run id
}

type ReadRequest_Log struct {
	Log string `protobuf:"bytes,3,opt,name=log,proto3,oneof"` // a machine log's name
}

func (*ReadRequest_Output) isReadRequest_Target() {}

func (*ReadRequest_Triage) isReadRequest_Target() {}

func (*ReadRequest_Log) isReadRequest_Target() {}

type OutputTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           string                 `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"` // a list item's 1-based index; 0 for a single output
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputTarget) Reset() {
	*x = OutputTarget{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputTarget) ProtoMessage() {}

func (x *OutputTarget) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputTarget.ProtoReflect.Descriptor instead.
func (*OutputTarget) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{19}
}

func (x *OutputTarget) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

func (x *OutputTarget) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *OutputTarget) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// The first frame describes the bytes (data may be empty); the rest carry data in order.
type ReadFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rev           uint64                 `protobuf:"varint,1,opt,name=rev,proto3" json:"rev,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"` // sha256:<hex>, once the output is final
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFrame) Reset() {
	*x = ReadFrame{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFrame) ProtoMessage() {}

func (x *ReadFrame) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFrame.ProtoReflect.Descriptor instead.
func (*ReadFrame) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{20}
}

func (x *ReadFrame) GetRev() uint64 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *ReadFrame) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ReadFrame) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ReadFrame) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ReadFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Without a machine-scope cap Status answers one frame (identity and the sealed receipt) and
// ends. With one it streams: each frame is the whole picture, sent again when it changes. An
// open Status stream is not activity; `keepalive` resets the idle deadline once and the first
// frame carries the new deadline.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keepalive     bool                   `protobuf:"varint,1,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{21}
}

func (x *StatusRequest) GetKeepalive() bool {
	if x != nil {
		return x.Keepalive
	}
	return false
}

type StatusFrame struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	BootId             string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Version            string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // this machine's release
	Capabilities       []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Receipt            []byte                 `protobuf:"bytes,5,opt,name=receipt,proto3" json:"receipt,omitempty"`                                                      // the sealed readiness envelope; empty until sealed
	IdleDeadlineUnixMs int64                  `protobuf:"varint,6,opt,name=idle_deadline_unix_ms,json=idleDeadlineUnixMs,proto3" json:"idle_deadline_unix_ms,omitempty"` // 0: no idle release
	Runs               []*RunState            `protobuf:"bytes,7,rep,name=runs,proto3" json:"runs,omitempty"`                                                            // the caller's live runs
	Phase              string                 `protobuf:"bytes,8,opt,name=phase,proto3" json:"phase,omitempty"`                                                          // booting, ready, releasing
	Platform           string                 `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`                                                    // os/arch
	StartedAtUnixMs    int64                  `protobuf:"varint,10,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	Gpus               []*Gpu                 `protobuf:"bytes,11,rep,name=gpus,proto3" json:"gpus,omitempty"` // measured at boot
	Hubs               []*Hub                 `protobuf:"bytes,12,rep,name=hubs,proto3" json:"hubs,omitempty"`
	Runtime            string                 `protobuf:"bytes,13,opt,name=runtime,proto3" json:"runtime,omitempty"` // the executors' cozy-runtime
	Tensorfs           string                 `protobuf:"bytes,14,opt,name=tensorfs,proto3" json:"tensorfs,omitempty"`
	Environments       []*Environment         `protobuf:"bytes,15,rep,name=environments,proto3" json:"environments,omitempty"` // the caller's held package installations
	Disk               *Disk                  `protobuf:"bytes,16,opt,name=disk,proto3" json:"disk,omitempty"`                 // the filesystem holding the machine's store
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusFrame) Reset() {
	*x = StatusFrame{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusFrame) ProtoMessage() {}

func (x *StatusFrame) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusFrame.ProtoReflect.Descriptor instead.
func (*StatusFrame) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{22}
}

func (x *StatusFrame) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *StatusFrame) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *StatusFrame) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusFrame) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *StatusFrame) GetReceipt() []byte {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *StatusFrame) GetIdleDeadlineUnixMs() int64 {
	if x != nil {
		return x.IdleDeadlineUnixMs
	}
	return 0
}

func (x *StatusFrame) GetRuns() []*RunState {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *StatusFrame) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *StatusFrame) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *StatusFrame) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *StatusFrame) GetGpus() []*Gpu {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *StatusFrame) GetHubs() []*Hub {
	if x != nil {
		return x.Hubs
	}
	return nil
}

func (x *StatusFrame) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *StatusFrame) GetTensorfs() string {
	if x != nil {
		return x.Tensorfs
	}
	return ""
}

func (x *StatusFrame) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *StatusFrame) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type Gpu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PciBusId      string                 `protobuf:"bytes,4,opt,name=pci_bus_id,json=pciBusId,proto3" json:"pci_bus_id,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Driver        string                 `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gpu) Reset() {
	*x = Gpu{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gpu) ProtoMessage() {}

func (x *Gpu) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gpu.ProtoReflect.Descriptor instead.
func (*Gpu) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{23}
}

func (x *Gpu) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Gpu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gpu) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Gpu) GetPciBusId() string {
	if x != nil {
		return x.PciBusId
	}
	return ""
}

func (x *Gpu) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Gpu) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type Hub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	MachineId     string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // this machine's worker id there
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hub) Reset() {
	*x = Hub{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hub) ProtoMessage() {}

func (x *Hub) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hub.ProtoReflect.Descriptor instead.
func (*Hub) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{24}
}

func (x *Hub) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Hub) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installation  string                 `protobuf:"bytes,1,opt,name=installation,proto3" json:"installation,omitempty"` // RunSpec.installation names it
	Package       string                 `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Release       string                 `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	Entrypoints   []string               `protobuf:"bytes,4,rep,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	Runtime       string                 `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"` // the cozy-runtime installed in it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{25}
}

func (x *Environment) GetInstallation() string {
	if x != nil {
		return x.Installation
	}
	return ""
}

func (x *Environment) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Environment) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *Environment) GetEntrypoints() []string {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

func (x *Environment) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,2,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{26}
}

func (x *Disk) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Disk) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

// The first frame names the object; frames carry its bytes from `offset` (the length the
// machine already holds, from WriteResult or a previous attempt).
type WriteFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"` // sha256:<hex>
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFrame) Reset() {
	*x = WriteFrame{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFrame) ProtoMessage() {}

func (x *WriteFrame) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFrame.ProtoReflect.Descriptor instead.
func (*WriteFrame) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{27}
}

func (x *WriteFrame) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *WriteFrame) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *WriteFrame) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Held          uint64                 `protobuf:"varint,2,opt,name=held,proto3" json:"held,omitempty"` // bytes held; equal to length once complete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResult) Reset() {
	*x = WriteResult{}
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResult) ProtoMessage() {}

func (x *WriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_cozy_machine_v1_machine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResult.ProtoReflect.Descriptor instead.
func (*WriteResult) Descriptor() ([]byte, []int) {
	return file_cozy_machine_v1_machine_proto_rawDescGZIP(), []int{28}
}

func (x *WriteResult) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *WriteResult) GetHeld() uint64 {
	if x != nil {
		return x.Held
	}
	return 0
}

var File_cozy_machine_v1_machine_proto protoreflect.FileDescriptor

const file_cozy_machine_v1_machine_proto_rawDesc = "" +
	"\n" +
	"\x1dcozy/machine/v1/machine.proto\x12\x0fcozy.machine.v1\"`\n" +
	"\n" +
	"RunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\x12,\n" +
	"\x04spec\x18\x03 \x01(\v2\x18.cozy.machine.v1.RunSpecR\x04spec\"\x84\x05\n" +
	"\aRunSpec\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.cozy.machine.v1.RunKindR\x04kind\x124\n" +
	"\arelease\x18\x02 \x01(\v2\x18.cozy.machine.v1.ReleaseH\x00R\arelease\x12$\n" +
	"\finstallation\x18\x03 \x01(\tH\x00R\finstallation\x124\n" +
	"\x05local\x18\x04 \x01(\v2\x1c.cozy.machine.v1.LocalSourceH\x00R\x05local\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x01(\tR\n" +
	"entrypoint\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x122\n" +
	"\x06inputs\x18\b \x03(\v2\x1a.cozy.machine.v1.InputFileR\x06inputs\x124\n" +
	"\x06models\x18\t \x03(\v2\x1c.cozy.machine.v1.ModelChoiceR\x06models\x12)\n" +
	"\x10binding_revision\x18\n" +
	" \x01(\tR\x0fbindingRevision\x12@\n" +
	"\rknown_results\x18\v \x03(\v2\x1b.cozy.machine.v1.MemoResultR\fknownResults\x12)\n" +
	"\x10attention_kernel\x18\f \x01(\tR\x0fattentionKernel\x12/\n" +
	"\x13weights_destination\x18\r \x01(\tR\x12weightsDestination\x12,\n" +
	"\x03hub\x18\x0e \x01(\v2\x1a.cozy.machine.v1.HubAccessR\x03hub\x12\x14\n" +
	"\x05owner\x18\x0f \x01(\tR\x05ownerB\b\n" +
	"\x06source\"=\n" +
	"\aRelease\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x18\n" +
	"\arelease\x18\x02 \x01(\tR\arelease\")\n" +
	"\vLocalSource\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\tR\bmanifest\"\x86\x01\n" +
	"\tInputFile\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05order\x18\x05 \x01(\rR\x05order\"\xf4\x01\n" +
	"\vModelChoice\x12\x1c\n" +
	"\tparameter\x18\x01 \x01(\tR\tparameter\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x18\n" +
	"\arelease\x18\x03 \x01(\tR\arelease\x12\x12\n" +
	"\x04lane\x18\x04 \x01(\tR\x04lane\x12\x1a\n" +
	"\bmanifest\x18\x05 \x01(\tR\bmanifest\x12'\n" +
	"\x0fmanifest_length\x18\x06 \x01(\x04R\x0emanifestLength\x124\n" +
	"\badapters\x18\a \x03(\v2\x18.cozy.machine.v1.AdapterR\badapters\"\x9d\x01\n" +
	"\aAdapter\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x18\n" +
	"\arelease\x18\x03 \x01(\tR\arelease\x12\x12\n" +
	"\x04lane\x18\x04 \x01(\tR\x04lane\x12\x1a\n" +
	"\bmanifest\x18\x05 \x01(\tR\bmanifest\x12\x14\n" +
	"\x05scale\x18\x06 \x01(\tR\x05scale\"q\n" +
	"\n" +
	"MemoResult\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12-\n" +
	"\x12computation_digest\x18\x02 \x01(\tR\x11computationDigest\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\"\x92\x01\n" +
	"\tHubAccess\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x15\n" +
	"\x06ca_der\x18\x04 \x01(\fR\x05caDer\x12!\n" +
	"\fobject_hosts\x18\x05 \x03(\tR\vobjectHosts\"\xfd\x02\n" +
	"\bRunEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x13\n" +
	"\x05at_ms\x18\x02 \x01(\x03R\x04atMs\x121\n" +
	"\x05state\x18\x03 \x01(\v2\x19.cozy.machine.v1.RunStateH\x00R\x05state\x127\n" +
	"\bprogress\x18\x04 \x01(\v2\x19.cozy.machine.v1.ProgressH\x00R\bprogress\x124\n" +
	"\aproduct\x18\x05 \x01(\v2\x18.cozy.machine.v1.ProductH\x00R\aproduct\x12,\n" +
	"\x03log\x18\x06 \x01(\v2\x18.cozy.machine.v1.LogLineH\x00R\x03log\x124\n" +
	"\aoutcome\x18\a \x01(\v2\x18.cozy.machine.v1.OutcomeH\x00R\aoutcome\x121\n" +
	"\x04memo\x18\b \x01(\v2\x1b.cozy.machine.v1.MemoRecordH\x00R\x04memoB\a\n" +
	"\x05event\"\x98\x01\n" +
	"\bRunState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\x12\x18\n" +
	"\awaiting\x18\x06 \x01(\tR\awaiting\"\xb0\x01\n" +
	"\bProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1a\n" +
	"\bfraction\x18\x02 \x01(\x01R\bfraction\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\x04R\tcompleted\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x04R\x05total\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\x05 \x01(\x04R\tbytesDone\x12\x1f\n" +
	"\vbytes_total\x18\x06 \x01(\x04R\n" +
	"bytesTotal\"\xcf\x01\n" +
	"\aProduct\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x10\n" +
	"\x03rev\x18\x03 \x01(\x04R\x03rev\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05label\x18\a \x01(\tR\x05label\x12\x1f\n" +
	"\vduration_us\x18\b \x01(\x04R\n" +
	"durationUs\"3\n" +
	"\aLogLine\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xb6\x01\n" +
	"\aOutcome\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12/\n" +
	"\x06reason\x18\x02 \x01(\v2\x17.cozy.machine.v1.ReasonR\x06reason\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x122\n" +
	"\aoutputs\x18\x04 \x03(\v2\x18.cozy.machine.v1.ProductR\aoutputs\x12\x16\n" +
	"\x06triage\x18\x05 \x01(\bR\x06triage\"N\n" +
	"\x06Reason\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\"q\n" +
	"\n" +
	"MemoRecord\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12-\n" +
	"\x12computation_digest\x18\x02 \x01(\tR\x11computationDigest\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\"Q\n" +
	"\x0eControlRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06action\x18\x02 \x01(\x0e2\x17.cozy.machine.v1.ActionR\x06action\"\xc1\x01\n" +
	"\vReadRequest\x127\n" +
	"\x06output\x18\x01 \x01(\v2\x1d.cozy.machine.v1.OutputTargetH\x00R\x06output\x12\x18\n" +
	"\x06triage\x18\x02 \x01(\tH\x00R\x06triage\x12\x12\n" +
	"\x03log\x18\x03 \x01(\tH\x00R\x03log\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x15\n" +
	"\x06if_rev\x18\x05 \x01(\x04R\x05ifRev\x12\x12\n" +
	"\x04tail\x18\x06 \x01(\x04R\x04tailB\b\n" +
	"\x06target\"N\n" +
	"\fOutputTarget\x12\x10\n" +
	"\x03run\x18\x01 \x01(\tR\x03run\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\"\x80\x01\n" +
	"\tReadFrame\x12\x10\n" +
	"\x03rev\x18\x01 \x01(\x04R\x03rev\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"-\n" +
	"\rStatusRequest\x12\x1c\n" +
	"\tkeepalive\x18\x01 \x01(\bR\tkeepalive\"\xd3\x04\n" +
	"\vStatusFrame\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x18\n" +
	"\areceipt\x18\x05 \x01(\fR\areceipt\x121\n" +
	"\x15idle_deadline_unix_ms\x18\x06 \x01(\x03R\x12idleDeadlineUnixMs\x12-\n" +
	"\x04runs\x18\a \x03(\v2\x19.cozy.machine.v1.RunStateR\x04runs\x12\x14\n" +
	"\x05phase\x18\b \x01(\tR\x05phase\x12\x1a\n" +
	"\bplatform\x18\t \x01(\tR\bplatform\x12+\n" +
	"\x12started_at_unix_ms\x18\n" +
	" \x01(\x03R\x0fstartedAtUnixMs\x12(\n" +
	"\x04gpus\x18\v \x03(\v2\x14.cozy.machine.v1.GpuR\x04gpus\x12(\n" +
	"\x04hubs\x18\f \x03(\v2\x14.cozy.machine.v1.HubR\x04hubs\x12\x18\n" +
	"\aruntime\x18\r \x01(\tR\aruntime\x12\x1a\n" +
	"\btensorfs\x18\x0e \x01(\tR\btensorfs\x12@\n" +
	"\fenvironments\x18\x0f \x03(\v2\x1c.cozy.machine.v1.EnvironmentR\fenvironments\x12)\n" +
	"\x04disk\x18\x10 \x01(\v2\x15.cozy.machine.v1.DiskR\x04disk\"\x9c\x01\n" +
	"\x03Gpu\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x1c\n" +
	"\n" +
	"pci_bus_id\x18\x04 \x01(\tR\bpciBusId\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x16\n" +
	"\x06driver\x18\x06 \x01(\tR\x06driver\"<\n" +
	"\x03Hub\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\"\xa1\x01\n" +
	"\vEnvironment\x12\"\n" +
	"\finstallation\x18\x01 \x01(\tR\finstallation\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12\x18\n" +
	"\arelease\x18\x03 \x01(\tR\arelease\x12 \n" +
	"\ventrypoints\x18\x04 \x03(\tR\ventrypoints\x12\x18\n" +
	"\aruntime\x18\x05 \x01(\tR\aruntime\"F\n" +
	"\x04Disk\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x02 \x01(\x04R\tfreeBytes\"h\n" +
	"\n" +
	"WriteFrame\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"9\n" +
	"\vWriteResult\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x12\n" +
	"\x04held\x18\x02 \x01(\x04R\x04held*V\n" +
	"\aRunKind\x12\x11\n" +
	"\rRUN_KIND_CALL\x10\x00\x12\x10\n" +
	"\fRUN_KIND_JOB\x10\x01\x12\x11\n" +
	"\rRUN_KIND_WARM\x10\x02\x12\x13\n" +
	"\x0fRUN_KIND_UPDATE\x10\x03*X\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_CANCEL\x10\x01\x12\x10\n" +
	"\fACTION_PAUSE\x10\x02\x12\x11\n" +
	"\rACTION_RESUME\x10\x032\xe5\x02\n" +
	"\aMachine\x12H\n" +
	"\x06Status\x12\x1e.cozy.machine.v1.StatusRequest\x1a\x1c.cozy.machine.v1.StatusFrame0\x01\x12?\n" +
	"\x03Run\x12\x1b.cozy.machine.v1.RunRequest\x1a\x19.cozy.machine.v1.RunEvent0\x01\x12E\n" +
	"\aControl\x12\x1f.cozy.machine.v1.ControlRequest\x1a\x19.cozy.machine.v1.RunState\x12B\n" +
	"\x04Read\x12\x1c.cozy.machine.v1.ReadRequest\x1a\x1a.cozy.machine.v1.ReadFrame0\x01\x12D\n" +
	"\x05Write\x12\x1b.cozy.machine.v1.WriteFrame\x1a\x1c.cozy.machine.v1.WriteResult(\x01b\x06proto3"

var (
	file_cozy_machine_v1_machine_proto_rawDescOnce sync.Once
	file_cozy_machine_v1_machine_proto_rawDescData []byte
)

func file_cozy_machine_v1_machine_proto_rawDescGZIP() []byte {
	file_cozy_machine_v1_machine_proto_rawDescOnce.Do(func() {
		file_cozy_machine_v1_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cozy_machine_v1_machine_proto_rawDesc), len(file_cozy_machine_v1_machine_proto_rawDesc)))
	})
	return file_cozy_machine_v1_machine_proto_rawDescData
}

var file_cozy_machine_v1_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cozy_machine_v1_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_cozy_machine_v1_machine_proto_goTypes = []any{
	(RunKind)(0),           // 0: cozy.machine.v1.RunKind
	(Action)(0),            // 1: cozy.machine.v1.Action
	(*RunRequest)(nil),     // 2: cozy.machine.v1.RunRequest
	(*RunSpec)(nil),        // 3: cozy.machine.v1.RunSpec
	(*Release)(nil),        // 4: cozy.machine.v1.Release
	(*LocalSource)(nil),    // 5: cozy.machine.v1.LocalSource
	(*InputFile)(nil),      // 6: cozy.machine.v1.InputFile
	(*ModelChoice)(nil),    // 7: cozy.machine.v1.ModelChoice
	(*Adapter)(nil),        // 8: cozy.machine.v1.Adapter
	(*MemoResult)(nil),     // 9: cozy.machine.v1.MemoResult
	(*HubAccess)(nil),      // 10: cozy.machine.v1.HubAccess
	(*RunEvent)(nil),       // 11: cozy.machine.v1.RunEvent
	(*RunState)(nil),       // 12: cozy.machine.v1.RunState
	(*Progress)(nil),       // 13: cozy.machine.v1.Progress
	(*Product)(nil),        // 14: cozy.machine.v1.Product
	(*LogLine)(nil),        // 15: cozy.machine.v1.LogLine
	(*Outcome)(nil),        // 16: cozy.machine.v1.Outcome
	(*Reason)(nil),         // 17: cozy.machine.v1.Reason
	(*MemoRecord)(nil),     // 18: cozy.machine.v1.MemoRecord
	(*ControlRequest)(nil), // 19: cozy.machine.v1.ControlRequest
	(*ReadRequest)(nil),    // 20: cozy.machine.v1.ReadRequest
	(*OutputTarget)(nil),   // 21: cozy.machine.v1.OutputTarget
	(*ReadFrame)(nil),      // 22: cozy.machine.v1.ReadFrame
	(*StatusRequest)(nil),  // 23: cozy.machine.v1.StatusRequest
	(*StatusFrame)(nil),    // 24: cozy.machine.v1.StatusFrame
	(*Gpu)(nil),            // 25: cozy.machine.v1.Gpu
	(*Hub)(nil),            // 26: cozy.machine.v1.Hub
	(*Environment)(nil),    // 27: cozy.machine.v1.Environment
	(*Disk)(nil),           // 28: cozy.machine.v1.Disk
	(*WriteFrame)(nil),     // 29: cozy.machine.v1.WriteFrame
	(*WriteResult)(nil),    // 30: cozy.machine.v1.WriteResult
}
var file_cozy_machine_v1_machine_proto_depIdxs = []int32{
	3,  // 0: cozy.machine.v1.RunRequest.spec:type_name -> cozy.machine.v1.RunSpec
	0,  // 1: cozy.machine.v1.RunSpec.kind:type_name -> cozy.machine.v1.RunKind
	4,  // 2: cozy.machine.v1.RunSpec.release:type_name -> cozy.machine.v1.Release
	5,  // 3: cozy.machine.v1.RunSpec.local:type_name -> cozy.machine.v1.LocalSource
	6,  // 4: cozy.machine.v1.RunSpec.inputs:type_name -> cozy.machine.v1.InputFile
	7,  // 5: cozy.machine.v1.RunSpec.models:type_name -> cozy.machine.v1.ModelChoice
	9,  // 6: cozy.machine.v1.RunSpec.known_results:type_name -> cozy.machine.v1.MemoResult
	10, // 7: cozy.machine.v1.RunSpec.hub:type_name -> cozy.machine.v1.HubAccess
	8,  // 8: cozy.machine.v1.ModelChoice.adapters:type_name -> cozy.machine.v1.Adapter
	12, // 9: cozy.machine.v1.RunEvent.state:type_name -> cozy.machine.v1.RunState
	13, // 10: cozy.machine.v1.RunEvent.progress:type_name -> cozy.machine.v1.Progress
	14, // 11: cozy.machine.v1.RunEvent.product:type_name -> cozy.machine.v1.Product
	15, // 12: cozy.machine.v1.RunEvent.log:type_name -> cozy.machine.v1.LogLine
	16, // 13: cozy.machine.v1.RunEvent.outcome:type_name -> cozy.machine.v1.Outcome
	18, // 14: cozy.machine.v1.RunEvent.memo:type_name -> cozy.machine.v1.MemoRecord
	17, // 15: cozy.machine.v1.Outcome.reason:type_name -> cozy.machine.v1.Reason
	14, // 16: cozy.machine.v1.Outcome.outputs:type_name -> cozy.machine.v1.Product
	1,  // 17: cozy.machine.v1.ControlRequest.action:type_name -> cozy.machine.v1.Action
	21, // 18: cozy.machine.v1.ReadRequest.output:type_name -> cozy.machine.v1.OutputTarget
	12, // 19: cozy.machine.v1.StatusFrame.runs:type_name -> cozy.machine.v1.RunState
	25, // 20: cozy.machine.v1.StatusFrame.gpus:type_name -> cozy.machine.v1.Gpu
	26, // 21: cozy.machine.v1.StatusFrame.hubs:type_name -> cozy.machine.v1.Hub
	27, // 22: cozy.machine.v1.StatusFrame.environments:type_name -> cozy.machine.v1.Environment
	28, // 23: cozy.machine.v1.StatusFrame.disk:type_name -> cozy.machine.v1.Disk
	23, // 24: cozy.machine.v1.Machine.Status:input_type -> cozy.machine.v1.StatusRequest
	2,  // 25: cozy.machine.v1.Machine.Run:input_type -> cozy.machine.v1.RunRequest
	19, // 26: cozy.machine.v1.Machine.Control:input_type -> cozy.machine.v1.ControlRequest
	20, // 27: cozy.machine.v1.Machine.Read:input_type -> cozy.machine.v1.ReadRequest
	29, // 28: cozy.machine.v1.Machine.Write:input_type -> cozy.machine.v1.WriteFrame
	24, // 29: cozy.machine.v1.Machine.Status:output_type -> cozy.machine.v1.StatusFrame
	11, // 30: cozy.machine.v1.Machine.Run:output_type -> cozy.machine.v1.RunEvent
	12, // 31: cozy.machine.v1.Machine.Control:output_type -> cozy.machine.v1.RunState
	22, // 32: cozy.machine.v1.Machine.Read:output_type -> cozy.machine.v1.ReadFrame
	30, // 33: cozy.machine.v1.Machine.Write:output_type -> cozy.machine.v1.WriteResult
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_cozy_machine_v1_machine_proto_init() }
func file_cozy_machine_v1_machine_proto_init() {
	if File_cozy_machine_v1_machine_proto != nil {
		return
	}
	file_cozy_machine_v1_machine_proto_msgTypes[1].OneofWrappers = []any{
		(*RunSpec_Release)(nil),
		(*RunSpec_Installation)(nil),
		(*RunSpec_Local)(nil),
	}
	file_cozy_machine_v1_machine_proto_msgTypes[9].OneofWrappers = []any{
		(*RunEvent_State)(nil),
		(*RunEvent_Progress)(nil),
		(*RunEvent_Product)(nil),
		(*RunEvent_Log)(nil),
		(*RunEvent_Outcome)(nil),
		(*RunEvent_Memo)(nil),
	}
	file_cozy_machine_v1_machine_proto_msgTypes[18].OneofWrappers = []any{
		(*ReadRequest_Output)(nil),
		(*ReadRequest_Triage)(nil),
		(*ReadRequest_Log)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cozy_machine_v1_machine_proto_rawDesc), len(file_cozy_machine_v1_machine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cozy_machine_v1_machine_proto_goTypes,
		DependencyIndexes: file_cozy_machine_v1_machine_proto_depIdxs,
		EnumInfos:         file_cozy_machine_v1_machine_proto_enumTypes,
		MessageInfos:      file_cozy_machine_v1_machine_proto_msgTypes,
	}.Build()
	File_cozy_machine_v1_machine_proto = out.File
	file_cozy_machine_v1_machine_proto_goTypes = nil
	file_cozy_machine_v1_machine_proto_depIdxs = nil
}
